---
ocp4_workload_external_secrets_helm_cli_version: v3.18.4
ocp4_workload_external_secrets_namespace: external-secrets
ocp4_workload_external_secrets_helm_repo: https://charts.external-secrets.io
ocp4_workload_external_secrets_helm_chart: external-secrets/external-secrets
ocp4_workload_external_secrets_helm_chart_version: 0.9.2

ocp4_workload_external_secrets_vault_namespace: vault