---
# Namespace configuration
ocp4_workload_trusted_artifact_signer_namespace: trusted-artifact-signer
ocp4_workload_trusted_artifact_signer_operator_namespace: openshift-operators

# Operator configuration
ocp4_workload_trusted_artifact_signer_channel: stable-v1.3
ocp4_workload_trusted_artifact_signer_starting_csv: ""
ocp4_workload_trusted_artifact_signer_automatic_install_plan_approval: true
ocp4_workload_trusted_artifact_signer_use_catalog_source: true
ocp4_workload_trusted_artifact_signer_catalogsource_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_trusted_artifact_signer_catalogsource_tag: v4.19_2025_10_23

# Keycloak configuration
ocp4_workload_trusted_artifact_signer_keycloak_namespace: sso
ocp4_workload_trusted_artifact_signer_sso_realm: sso
ocp4_workload_trusted_artifact_signer_client_id: trusted-artifact-signer