---
# Namespace configuration
ocp4_workload_trusted_profile_analyzer_namespace: trusted-profile-analyzer

# Operator configuration
ocp4_workload_trusted_profile_analyzer_channel: stable-v1.0
ocp4_workload_trusted_profile_analyzer_automatic_install_plan_approval: true
ocp4_workload_trusted_profile_analyzer_starting_csv: ""
ocp4_workload_trusted_profile_analyzer_use_catalog_source: true
ocp4_workload_trusted_profile_analyzer_catalogsource_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_trusted_profile_analyzer_catalogsource_tag: v4.19_2025_10_23

# Database configuration
ocp4_workload_trusted_profile_analyzer_pgsql_password: "password"

# Keycloak configuration
ocp4_workload_trusted_profile_analyzer_keycloak_namespace: sso
ocp4_workload_trusted_profile_analyzer_keycloak_realm: tpa
ocp4_workload_trusted_profile_analyzer_admin_username: "tpa-admin"
ocp4_workload_trusted_profile_analyzer_admin_password: "openshift"

# TPA Client configuration
ocp4_workload_trusted_profile_analyzer_keycloak_cli_client_secret: "5460cc91-4e20-4edd-881c-b15b169f8a79"

# User configuration
ocp4_workload_trusted_profile_analyzer_username_base: user
ocp4_workload_trusted_profile_analyzer_num_users: 1