---
ocp4_workload_advanced_developer_suite_tssc_namespace: tssc
ocp4_workload_advanced_developer_suite_rhtas_cli_server_namespace: trusted-artifact-signer
ocp4_workload_advanced_developer_suite_rhtas_cli_server_image: registry.redhat.io/rhtas/client-server-rhel9:1.3.2

ocp4_workload_advanced_developer_suite_tssc_cli_repo: https://github.com/redhat-appstudio/rhtap-cli
ocp4_workload_advanced_developer_suite_tssc_cli_revision: release-1.6

ocp4_workload_advanced_developer_suite_keycloak_namespace: tssc-keycloak
ocp4_workload_advanced_developer_suite_dh_namespace: tssc-dh

ocp4_workload_advanced_developer_suite_user_base_name: user
ocp4_workload_advanced_developer_suite_user_password: password
ocp4_workload_advanced_developer_suite_user_count: "{{ num_users | default(1) }}"

ocp4_workload_advanced_developer_suite_admin_user: admin
ocp4_workload_advanced_developer_suite_admin_password: password
ocp4_workload_advanced_developer_suite_remove_kubeadmin: true

ocp4_workload_advanced_developer_suite_openshift_keycloak_client_id: idp-4-ocp
ocp4_workload_advanced_developer_suite_openshift_keycloak_client_secret: password
ocp4_workload_advanced_developer_suite_dh_keycloak_client_id: rhdh
ocp4_workload_advanced_developer_suite_dh_keycloak_client_secret: password
ocp4_workload_advanced_developer_suite_dh_dynamic_plugins_enable:
- package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
  disabled: false
- package: ./dynamic-plugins/dist/backstage-community-plugin-ocm
  disabled: false
- package: ./dynamic-plugins/dist/backstage-community-plugin-ocm-backend-dynamic
  disabled: false

ocp4_workload_advanced_developer_suite_dh_orchestrator_enabled: true
ocp4_workload_advanced_developer_suite_dh_orchestrator_plugins_enable:
- disabled: false
  integrity: sha512-9cXbedr0lC7ns7SNqARrWSQI4JGcZFw5xpfpUzA1tJaMMUjzAdPHTXqljf62/fs4hYBK8TJsWJ2KJkGVMzbrHQ==
  package: '@redhat/backstage-plugin-orchestrator-backend-dynamic@1.7.1'
  dependencies:
  - ref: sonataflow
- disabled: false
  integrity: sha512-Cqu9EQwVQ4mpdgWTUA0MW89Gul0IklhvkkqVoO3CloQ1dnAj1XyXikCphzH5TmNDDd9K66dOpaKKCaW9KeJ4WA==
  package: '@redhat/backstage-plugin-orchestrator@1.7.1'
  pluginConfig:
    dynamicPlugins:
      frontend:
        red-hat-developer-hub.backstage-plugin-orchestrator:
          appIcons:
          - importName: OrchestratorIcon
            name: orchestratorIcon
          dynamicRoutes:
          - importName: OrchestratorPage
            menuItem:
              icon: orchestratorIcon
              text: Orchestrator
            path: /orchestrator
- disabled: false
  integrity: sha512-J1sTjA5kj6DphG8D65go9KlpIfKyLN/wq+XlY5Cb5djEo8mvF3wn3Haf60OGFo5cP4OfRSWqFwT7LM5/dNVwAg==
  package: '@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.7.1'
  pluginConfig:
    orchestrator:
      dataIndexService:
        url: http://sonataflow-platform-data-index-service
- disabled: false
  integrity: sha512-0KIXrZoJ+O4xNNzN/zB4+VMuaRPuiUviAmM+fIhTo/P9aLA36F9aIlyMbUbki49uaJ0zd8KXMBvmJSHZNrYkGQ==
  package: '@redhat/backstage-plugin-orchestrator-form-widgets@1.7.1'
  pluginConfig:
    dynamicPlugins:
      frontend:
        red-hat-developer-hub.backstage-plugin-orchestrator-form-widgets: {}
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-notifications"
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-signals"
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic"
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic"

ocp4_workload_advanced_developer_suite_gitlab_namespace: gitlab
ocp4_workload_advanced_developer_suite_gitlab_root_email: root@demo.redhat.com
ocp4_workload_advanced_developer_suite_gitlab_root_user: root
ocp4_workload_advanced_developer_suite_dh_catalog_locations:
  repository: tssc-developer-hub-configuration
  branch: main
  group: rhdh
  file: all-locations.yaml

ocp4_workload_advanced_developer_suite_devspaces_namespace: openshift-devspaces

ocp4_workload_advanced_developer_suite_quay_namespace: quay-enterprise
ocp4_workload_advanced_developer_suite_quay_org_name: tssc
ocp4_workload_advanced_developer_suite_quay_admin_user: quayadmin
ocp4_workload_advanced_developer_suite_quay_admin_password: "{{ common_password | default('password') }}"

ocp4_workload_advanced_developer_suite_tssc_ci_namespace: tssc-app-ci

ocp4_workload_advanced_developer_suite_nginx_namespace: nginx

ocp4_workload_advanced_developer_suite_tssc_gitops_namespace: tssc-gitops

ocp4_workload_advanced_developer_suite_tssc_tpa_namespace: tssc-tpa

ocp4_workload_advanced_developer_suite_jenkins_namespace: jenkins
ocp4_workload_advanced_developer_suite_jenkins_admin_user: admin
ocp4_workload_advanced_developer_suite_jenkins_admin_password: password

ocp4_workload_advanced_developer_suite_acs_namespace: tssc-acs
ocp4_workload_advanced_developer_suite_acs_admin_user: admin
ocp4_workload_advanced_developer_suite_acs_enable_route_certs: false

ocp4_workload_advanced_developer_suite_disable_odf: false

ocp4_workload_advanced_developer_suite_helm_cli_version: v3.18.4
ocp4_workload_advanced_developer_suite_go_version: go1.26.0

# yamllint disable rule:line-length
ocp4_workload_advanced_developer_suite_orchestrator_workflows:
  repo: https://redhat-ads-tech.github.io/orchestrator-workflows
  chart:
  - name: greeting
    location: orchestrator-workflows/greeting
    customParameters: "--set-string=persistence.postgresql.secretRef.name=backstage-psql-secret-developer-hub --set-string=persistence.postgresql.serviceRef.name=backstage-psql-developer-hub"
# yamllint enable rule:line-length