---
# Implement your Workload removal tasks here

# TBD

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  ansible.builtin.debug:
    msg: "Remove Workload tasks completed successfully."
