---
- name: Add Orchestrator workflows repository
  ansible.builtin.shell: |
    helm repo add orchestrator-workflows {{
    ocp4_workload_advanced_developer_suite_orchestrator_workflows.repo }} --force-update

- name: Install Orchestrator workflows
  ansible.builtin.shell: |
    helm install {{ item.name }} {{ item.location }} {{
    item.customParameters }} -n {{
    ocp4_workload_advanced_developer_suite_dh_namespace }}
  loop: "{{ ocp4_workload_advanced_developer_suite_orchestrator_workflows.chart }}"
  register: r_orch_workflow
  until: r_orch_workflow is not failed
  retries: 120
  delay: 10
