---
- name: Create group tssc
  uri:
    url: https://sso.{{ _ocp_apps_domain }}/admin/realms/tssc-iam/groups
    method: POST
    validate_certs: false
    body_format: json
    headers:
      Authorization: Bearer {{ _keycloak_access_token }}
    body:
      name: tssc
    status_code: 201

- name: Get group tssc
  uri:
    url: https://sso.{{ _ocp_apps_domain }}/admin/realms/tssc-iam/groups?search=tssc
    method: GET
    validate_certs: false
    headers:
      Authorization: Bearer {{ _keycloak_access_token }}
  register: r_keycloak_groups

- name: Set keycloak group id
  set_fact:
    _keycloak_group_id: "{{ r_keycloak_groups.json[0].id }}"