---
# yamllint disable rule:line-length
- name: Enable dynamic plugins
  set_fact:
    _dh_dyn_plg: "{{ _dh_dyn_plg | combine({'plugins': _dh_dyn_plg.plugins + ocp4_workload_advanced_developer_suite_dh_dynamic_plugins_enable}) }}"

- name: Update fact if orchestrator enabled
  when: ocp4_workload_advanced_developer_suite_dh_orchestrator_enabled
  set_fact:
    _dh_dyn_plg: "{{ _dh_dyn_plg | combine({'plugins': _dh_dyn_plg.plugins + ocp4_workload_advanced_developer_suite_dh_orchestrator_plugins_enable}) }}"
# yamllint enable rule:line-length